language: python
python:
- '3.4'
- '3.5'
- '3.6'
- '3.7'
- '3.8'

bundler_args: "--retry 3"
install:
- pip install -r requirements.txt
- pip install coveralls
- pip install pytest
- pip install pytest-cov
- pip install pytest-pep8
- pip install pandas

script:
- coverage run --source ddcmath -m pytest -v
- coverage report

after_success: coveralls

deploy:
  provider: pypi
  user: ChristianTremblay
  password:
    secure: k/ri0zBt8xvqqpiBCoEIDhyHxVLJntY3xj3qhKqk1lf48t8j34g5yNi6yia8lbRTt5G8Du+6aZzrfhvHpi8vZ7iHkYXaMVb4+hrY41T3WFgmTR9E0/yZkrRo1dFvcssZ2CTKvTZ1VGueJjRrCGiV/jdfrfZxke0bINAiOh8kryKbbA3rFnOPq77LR4SF+EiSm4uYE4sPE5mpMqKqOf1Sea3e5gE1E3y314qOamFgPsidXMx5j3MG3/kNg0StxXPQOOojOhbv2sUt4iOoKesmQiHe7mHoZJjmHDgGv7QbSrnGRKuwUIFZzROmNt+T1VRg+hMF/BcFUDm4+k5svPZCnC19gCFoVgsuAPuaHtVCNCLmxTXAeUgtUk72c/q6k9OXkMMokDEy3IwuQ/4hdYrMQF+nZLgA7V7iy6LgxEZYqYv4XdMNRtZ3kACbzFDqLKf+4+iam4G1stA796c5xjvo1ekYoxH5budTeVMs4QcRxbzXgbzityumjWM/JkB0PkC8z77RnW4Kq9NxbwG/4O7GQYCVIpCEtXH5zM5OPVLb1i5u5iuRzlPQ4juvbgEfrh3fyeHM+o8C+Qzn7n9qmnnW9WVJNwVUl+OzMuYw6FVFEbQ8rRvU608b1hHF6rZMEs2gcbcOtoxBEh+egf1tDdvmIGvAalrv6Z8SBRH6GNEGmu0=
  on:
    branch: master
    python: '3.8'
    distributions: sdist bdist_wheel
    repo: ChristianTremblay/ddcmath
