language: python
python:
- '2.7'
- '3.3'
- '3.4'
- '3.5'
- 3.5-dev
- nightly
bundler_args: "--retry 3"
install:
- pip install -r requirements.txt
- pip install coveralls
- pip install pytest
- pip install pytest-cov
- pip install pytest-pep8
script:
- py.test -v --cov=ddcmath tests/
after_success: coveralls
deploy:
  provider: pypi
  user: ChristianTremblay
  password:
    secure: dVcOrDj0ys0poOYFmriMgnEwUbayN0o9+UZsmsP6NCYsgwQjGR+UZItInFrSXPSky2AH34XD+vR6cMFfkcDAhISi72iLHa+Y2degK5211HLYF6Wm1uRr0Tb7EdQgTb3HUjO8lLgwzAItIzmMRki/2Jj5hGVv68MYtp6Skxu1XGhiTZlwLrLhSzSgyXBJdf9xO0QkcUklshV8OwkYn7Suv8KapdjyGab8GkHMi6tI+ApyjehEXj6YW9bqRBVLTxhuws1VKmu6yqpXms8JTq4lPhUSRmS+QOhk2CaUvAhEWN2a8WNpzJ1pa8/kyY5SwInylI6VlE/49sMZOvGD5+L7KsCkM4j/L6FXdWD1We/ycAxShJTno90cP/azMc66Bp8qcu94Vg5HjBovs89YGld5BBJKSCNZHwHaxOnfWanE2wwcSwJHY2TwdS7lrDg52WCDdli0/H/6wLfvXiWsOyGVzaGrp+xdM6tDmaGYMAqzKB7CKpS9UZcaDSkhiTgs/oZRLKslo+LFw7NnBSvQxJMJIKaCDwE32sbCnHVDe23Pobb+DuMy1uIuPQqE7qeQr9S/V1qc8cHAf3+ODEIH72IzV47y9sdkO98VMNbUFGPwumXzdXkgsecAW+h+dG7X3qr+xtnkyQShvMqkVsDqD+dznDJ8Ui1NunVz5heehWyB/rE=
  on:
    distributions: sdist bdist_wheel
