language: python
python:
- '3.3'
- '3.4'
- '3.5'
- "3.5-dev" # 3.5 development branch
- "nightly" # currently points to 3.6-dev
bundler_args: "--retry 3"
install:
- pip install -r requirements.txt
- pip install coveralls
- pip install pytest
script:
- py.test -v --cov=ddcmath tests/
after_success: coveralls

deploy:
#- provider: pypi
#  server: https://testpypi.python.org/pypi
#  user: ChristianTremblay
#  password:
#    secure: C2RaknM+gjZ7IyzSs8Gh2IQAJVbG7/QSAGNQZAOirYQStUm9/KaLmHs8lUv7aEvNfE2NGCb/fE09kM7CzBlso3TGyl2tIT/Mc0mYlyEVlArzTEIMZ8UJKENnPYuV3Oj8pwLJzft2XLfYlPhG82FsMU6RcpKVrxOj9Z6nyXlvw+3ruljl9/KRQgG1S43CUuJXPP/DFiOAvPmlyiRDDgWgfyoNOMEHrHcyncBX4BTSD6NmY0VsdRk+Utas27gyGHwgS7nUCwSsFoGehHeJOiGHvajISPE2p8Z6uLVltsIeCEXFMzMqQtDC7D/xotK4BtQyz44ebiKeuSKUWl4v1tEfuQDMX7/KK4fH7d6irU2J26zGWoJKZB9+fbSE/3m0P1nJJeFhxXKbUqebhu03AhceiD/pSHCBT0UH+7JyWXmryHl5WlgGpN/VnNWOnxaZPrjbkqTOiu9btK66MFfBNsbGCtFw6FW+N+m9gp7Oh2orNHkdUv8svHxr4Qn8b45ejfiEGQPCkeedJ88xF/aXHlKlG1u5EI9ao43qNZRaXYtnEtnakcw5aIf0U5ukagK32zgv01X5JHoNPCf/ofnLAqpzW2f459iVwTIoamBVIz1B0zy8g/YEO2m6Sf0z1VoIWyoEFl4m/2ZagOjlEUCIhoSN84MX1e3KIj9o8oAKwvwWKXA=
#  distributions: sdist bdist_wheel
#  on:
#    branch: stage

- provider: pypi
  server: https://pypi.python.org/pypi
  user: ChristianTremblay
  password:
    secure: C2RaknM+gjZ7IyzSs8Gh2IQAJVbG7/QSAGNQZAOirYQStUm9/KaLmHs8lUv7aEvNfE2NGCb/fE09kM7CzBlso3TGyl2tIT/Mc0mYlyEVlArzTEIMZ8UJKENnPYuV3Oj8pwLJzft2XLfYlPhG82FsMU6RcpKVrxOj9Z6nyXlvw+3ruljl9/KRQgG1S43CUuJXPP/DFiOAvPmlyiRDDgWgfyoNOMEHrHcyncBX4BTSD6NmY0VsdRk+Utas27gyGHwgS7nUCwSsFoGehHeJOiGHvajISPE2p8Z6uLVltsIeCEXFMzMqQtDC7D/xotK4BtQyz44ebiKeuSKUWl4v1tEfuQDMX7/KK4fH7d6irU2J26zGWoJKZB9+fbSE/3m0P1nJJeFhxXKbUqebhu03AhceiD/pSHCBT0UH+7JyWXmryHl5WlgGpN/VnNWOnxaZPrjbkqTOiu9btK66MFfBNsbGCtFw6FW+N+m9gp7Oh2orNHkdUv8svHxr4Qn8b45ejfiEGQPCkeedJ88xF/aXHlKlG1u5EI9ao43qNZRaXYtnEtnakcw5aIf0U5ukagK32zgv01X5JHoNPCf/ofnLAqpzW2f459iVwTIoamBVIz1B0zy8g/YEO2m6Sf0z1VoIWyoEFl4m/2ZagOjlEUCIhoSN84MX1e3KIj9o8oAKwvwWKXA=
  distributions: sdist bdist_wheel
  on:
    branch: master